"""add_disease_profiles_table

Revision ID: 2a867e316341
Revises: bee2d164825f
Create Date: 2025-10-04 17:13:58.096241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a867e316341'
down_revision: Union[str, Sequence[str], None] = 'bee2d164825f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.String(length=100), nullable=False),
    sa.Column('disease_name', sa.String(length=200), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('common_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity_level', sa.Enum('MILD', 'MODERATE', 'SEVERE', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visual_symptoms_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('environmental_triggers_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('symptom_progression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_diagnostic_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('differential_diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnostic_confidence_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('treatment_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_profiles_category'), 'disease_profiles', ['category'], unique=False)
    op.create_index(op.f('ix_disease_profiles_disease_id'), 'disease_profiles', ['disease_id'], unique=True)
    op.create_index(op.f('ix_disease_profiles_disease_name'), 'disease_profiles', ['disease_name'], unique=False)
    op.create_index(op.f('ix_disease_profiles_id'), 'disease_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_profiles_id'), table_name='disease_profiles')
    op.drop_index(op.f('ix_disease_profiles_disease_name'), table_name='disease_profiles')
    op.drop_index(op.f('ix_disease_profiles_disease_id'), table_name='disease_profiles')
    op.drop_index(op.f('ix_disease_profiles_category'), table_name='disease_profiles')
    op.drop_table('disease_profiles')
    # ### end Alembic commands ###
