"""Create initial database schema

Revision ID: bee2d164825f
Revises: 
Create Date: 2025-09-20 10:18:38.047377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bee2d164825f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_table('orchards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.Column('address_detail', sa.String(), nullable=True),
    sa.Column('main_variety', sa.String(), nullable=True),
    sa.Column('avg_tree_age', sa.Integer(), nullable=True),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('last_harvest_date', sa.Date(), nullable=True),
    sa.Column('current_phenology', sa.String(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('has_new_alerts', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orchard_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('risk_item', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ignored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['orchard_id'], ['orchards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orchard_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('initial_query', sa.TEXT(), nullable=True),
    sa.Column('initial_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['orchard_id'], ['orchards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('primary_diagnosis', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('secondary_diagnoses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prevention_advice', sa.TEXT(), nullable=True),
    sa.Column('treatment_advice', sa.TEXT(), nullable=True),
    sa.Column('follow_up_plan', sa.TEXT(), nullable=True),
    sa.Column('original_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['diagnosis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('diagnosis_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('content_text', sa.TEXT(), nullable=True),
    sa.Column('content_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('agent_workflow_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['diagnosis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orchard_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('materials_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('effectiveness_rating', sa.String(), nullable=True),
    sa.Column('feedback_details', sa.TEXT(), nullable=True),
    sa.Column('follow_up_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['orchard_id'], ['orchards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farm_operations')
    op.drop_table('diagnosis_messages')
    op.drop_table('diagnoses')
    op.drop_table('diagnosis_sessions')
    op.drop_table('alerts')
    op.drop_table('orchards')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
